steps:
  - label: ":white_check_mark: Install"
    command: |
      echo "Install dependencies"
      pip3 install -r requirements-dev.txt
      pip3 install .
    key: install
  - label: ":rocket: Test"
    command: |
      make test
    depends_on: install
    env:
      PYTHONPATH: "."