steps:
  - label: ":white_check_mark: Install"
    command: |
      echo "Install dependencies"
      pip3 install -e .
      pip3 install -r requirements-dev.txt
    key: install
  - label: ":rocket: Test"
    command: |
      make test
    depends_on: install